---
title: "qc-power-analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
options(scipen = 999) # disable scientific notation)
library(sceptre)
library(ggplot2)
library(dplyr)
source("scripts/R/perturbplan_qc_utils.R")
sceptre_object <- readRDS("results/2025-09-19/sceptre_object.rds")
```

```{r}
register(MulticoreParam(workers = 8))
```

```{r}
# Compute baseline expression stats (dispersion and mean expression) for all genes
# The list of genes we are passing contains duplicates but inside the function we take
# the intersection with the genes present in the expression data, which removes duplicates.
message("Computing mean and dispersion for each gene.")
expression_stats <- calculate_expr_baseline(
  sceptre_object,
  genes = sceptre_object@discovery_pairs$response_id
  )

# Number of usable cells in the experiment
num_total_cells <- ncol(sceptre_object@response_matrix[[1]])
num_total_usable_cells <- length(sceptre_object@cells_in_use)
message("Total number of cells in the experiment: ", num_total_cells)
message("Number of usable cells in the experiment: ", num_total_usable_cells)
message("Fraction of usable cells: ", round(num_total_usable_cells / num_total_cells, 3))

# Get cells per guide RNA
number_of_cells_per_grna = mean(Matrix::rowSums(methods::as(sceptre::get_grna_assignments(sceptre_object, apply_cellwise_qc = FALSE),"dsparseMatrix")))

number_of_cells_per_grna_filtered = mean(Matrix::rowSums(methods::as(sceptre::get_grna_assignments(sceptre_object, apply_cellwise_qc = TRUE),"dsparseMatrix")))

message("Average number of cells per gRNA before QC: ", round(number_of_cells_per_grna,2))
message("Average number of cells per gRNA after QC: ", round(number_of_cells_per_grna_filtered,2))

# Create cells_per_grna table for perturbplan
cells_per_grna <- Matrix::rowSums(methods::as(sceptre::get_grna_assignments(sceptre_object, apply_cellwise_qc = TRUE),"dsparseMatrix"))
cells_per_grna <- data.table(grna_id = names(cells_per_grna), num_cells = cells_per_grna)

cells_per_grna <- merge(sceptre_object@grna_target_data_frame, cells_per_grna, by = "grna_id")


# Count number of guides per target
df = cells_per_grna %>% group_by(grna_target) %>%
  summarise(num_cel = sum(num_cells), guides = n()) %>%
  arrange(num_cel)

# Estimated number of cells per element
mean(cells_per_grna$num_cells) * number_of_cells_per_grna_filtered
# Observed number of cells per element
mean(df$num_cel)
```

```{r}

hist(expression_stats$expression_mean, breaks = 100,
     main = "Histogram of mean expression across genes",
     xlab = "Mean expression")
hist(expression_stats$expression_size, breaks = 100,
     main = "Histogram of dispersion across genes",
     xlab = "Dispersion")

n_readout_genes = nrow(expression_stats)

# Plot mean vs dispersion
ggplot(expression_stats, aes(expression_mean, expression_size)) +
  geom_point(alpha = 0.5, size = 1) +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "loess", se = FALSE, color = "firebrick") +
  labs(
    x = "Mean UMI counts",
    y = "theta (dispersion)",
    title = "Dispersion–mean trend (scale: log-log)",
    subtitle = sprintf("n = %d genes", n_readout_genes)
    ) +
  theme_minimal()



```

